# Docker Mongo:

#docker run -d -p 27017:27017 --network mongonet --name mongo -v ~/docker/mongo/data:/data/db mongo

#docker run -d -p 8081:8081 --network mongonet --name mongo-express mongo-express

#docker-compose -d -f docker.compose.yml up

version: '3.1'

networks:
  mongonet:
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - mongonet
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - mongonet

